### ISSUE TITLE
Bug: la suppression d'exemplaire ne fonctionne pas via le menu stock

### ISSUE THREAD

**Issue by Lavondysss** [biblys/biblys-theme-lavondyss#33]
J'ai besoin de supprimer les Galaxie deuxième série que j'ai en stock pour réuploader l'intégrale mais cliquer sur la fonction supprimer n'entraine absolument aucun effet. J'ai tenté sur plusieurs références, rien ne se passe.

**Comment by iwazaru** [comment]
Peux-tu me donner un exemple d'article que tu as voulu supprimer pour lequel ça n'a pas fonctionné ?

**Comment by Lavondysss** [comment]
Yep: j'ai tenté le coup sur tous les premiers Galaxie apparaissant LÀ
<https://lavondyss.biblys.fr/pages/adm_stocks?stock_insert=&availability=all&stock_invoice=JPTH+1800&stock_stockage=&publisher_id=&collection_id=&article_id=&type_id=&stock_condition=all&stock_limit=>
(soit les 115 116 117 118 quelque chose de ce goût là), pas de réaction. Le
bouton de duplication semble fonctionner cela dit. Aussi, il m'a semblé que
je pouvais changer le prix des bouquins à partir de cette interface, or, ce
n'est plus le cas.

**Comment by iwazaru** [comment]
Je viens de faire une mise à jour qui devrait corriger tous les problèmes que tu avais sur cette page.

**Comment by Lavondysss** [comment]
Super, ça marche ! Merci beaucoup !
