### ISSUE TITLE
Avoir une option de tri dans les résultats de recherche

### ISSUE THREAD

**Issue by iwazaru** [biblys/biblys-theme-lavondyss#5]
## d'après l'article :

- [x] date de parution
- [x] auteur
- [x] éditeur
- [x] collection

## d'après l'exemplaire :

- [ ] prix
- [ ] date d'ajout au stock

**Comment by Lavondysss** [comment]
Auteur / éditeur / collection / Date d'ajout / date de parution / Prix pour commencer ? :D

**Comment by iwazaru** [comment]
J'ai ajouté une première option de tri par date de parution (croissant ou décroissant). Pour les prochaines, ça devrait aller plus vite maintenant que j'ai le mécanisme (sauf pour la date d'ajout au stock où ça ne dépend pas de l'article mais de l'exemplaire, et donc là il faudra un nouveau "mécanisme"). Je vais attaquer les suivants dans l'ordre de la liste du premier message, mais n'hésite pas à les réordonner s'il y en a qui te semblent plus intéressant.

**Comment by Lavondysss** [comment]
Yo Clément,

Ça roule merci beaucoup ! J'ai jeté un petit coup d’œil et ça me semble
bien comme ça.

Le ven. 26 août 2022 à 12:33, Clément Bourgoin ***@***.***> a
écrit :

**Comment by Lavondysss** [comment]
Après quelques tests j'ai l'impression que le tri saute lorsque l'on change
de page de résultat !

**Comment by iwazaru** [comment]
Bien vu, c'est corrigé !

**Comment by iwazaru** [comment]
J'ai ajouté les mêmes options de tri que sur le site de Scylla, sauf le prix de vente et la date d'ajout, qui dépendent de l'exemplaire et donc c'est un tout autre sujet (pour lequel j'ai créé un ticket dédié : #36).

**Comment by Lavondysss** [comment]
Super, merci beaucoup !

Le ven. 2 sept. 2022 à 13:51, Clément Bourgoin ***@***.***> a
écrit :
